language: java

jdk:
  - oraclejdk8

script:
  - mvn clean deploy
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker push $DOCKER_USERNAME/cards-notification-service

services:
  - docker